# .github/workflows/release.yml
name: Release Package

on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed
    branches:
      - main   # Only trigger for pull requests targeting the main branch

permissions:
  contents: write # Needed to create GitHub releases
  issues: write # Needed to comment on issues/PRs linked in commits
  pull-requests: write # Needed to comment on issues/PRs linked in commits
  id-token: write # Needed for potential future OIDC auth

jobs:
  release:
    name: Create Release and Publish NPM Package
    # Add this condition to ensure the job only runs if the PR was merged
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      # IMPORTANT: Checkout the main branch AFTER the merge event
      # This ensures semantic-release runs on the correct branch history
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main # Explicitly check out the main branch
          # Set persist-credentials to false for semantic-release to use its own token for auth
          persist-credentials: false
          # Fetch all history for all tags and branches needed for semantic-release
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js version 20.x
          cache: 'npm' # Enable caching for npm dependencies

      - name: Install dependencies
        run: npm ci # Use ci for cleaner installs in CI

      - name: Build project
        run: npm run build # Run the build script defined in package.json

      - name: Run semantic-release
        run: npx semantic-release
        env:
          # Provide the tokens needed by semantic-release plugins
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions automatically
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Your secret NPM token 