# .github/workflows/release.yml
name: Release Package

on:
  push:
    branches:
      - main # Trigger only on pushes (including merges) to the main branch

permissions:
  contents: write # Needed to create GitHub releases
  issues: write # Needed to comment on issues/PRs linked in commits
  pull-requests: write # Needed to comment on issues/PRs linked in commits
  id-token: write # Needed for potential future OIDC auth

jobs:
  release:
    name: Create Release and Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      # IMPORTANT: Checkout the main branch
      # The trigger ensures this is the correct branch history
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          # No need to specify ref: main, it's implicit from the push trigger
          # Set persist-credentials to false for semantic-release to use its own token for auth
          persist-credentials: false
          # Fetch all history for all tags and branches needed for semantic-release
          fetch-depth: 0

      # 1️⃣ Install pnpm first so setup-node can find it
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # or whatever your repo uses
          run_install: false # we'll install after caching

      # 2️⃣ Install Node and enable pnpm-store caching
      - uses: actions/setup-node@v4
        with:
          node-version: "20" # Use Node.js version 20.x
          cache: "pnpm" # OK now – pnpm already on PATH

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # Use pnpm install

      - name: Build project
        run: pnpm run build # Run the build script defined in package.json

      - name: Run semantic-release
        run: npx semantic-release
        env:
          # Provide the tokens needed by semantic-release plugins
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions automatically
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Your secret NPM token
